---
# tasks for elasticsearch
- command: rpm --import http://packages.elasticsearch.org/GPG-KEY-elasticsearch

- template: src=./etc/yum.repos.d/elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo mode=0644 owner=root

- yum: name=java-1.7.0-openjdk-devel

- yum: name=elasticsearch

- service: name=elasticsearch state=started

- file: path=/etc/consul.d mode=0755 state=directory
  when: consul_enabled

- template: src=./etc/consul.d/elasticsearch.json dest=/etc/consul.d/elasticsearch.json
  when: consul_enabled
