---
# tasks for elasticsearch
- command: rpm --import http://packages.elasticsearch.org/GPG-KEY-elasticsearch
- template: src=templates/elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch.repo mode=0644 owner=root
- yum: name=elasticsearch
- service: name=elasticsearch state=started
- copy: src=./etc/consul.d/elasticsearch.json dest=/etc/consul.d/elasticsearch.json
  when: consul_enabled
